FROM php:8.2-fpm

# Instalar dependências do Laravel
RUN apt-get update && apt-get install -y \
    git unzip libonig-dev libxml2-dev zip curl \
    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath xml

# Instalar Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

# Copiar Laravel e instalar dependências
COPY ./ ./
RUN composer install --optimize-autoloader --no-dev

CMD ["php-fpm"]